# Generated by Django 5.2.7 on 2025-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
